# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: youlearn/api/pose_service.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='youlearn/api/pose_service.proto',
  package='youlearn.headpose.v1',
  syntax='proto3',
  serialized_options=b'\n\020com.youlearn.apiB\rHeadPoseProtoP\001',
  serialized_pb=b'\n\x1fyoulearn/api/pose_service.proto\x12\x14youlearn.headpose.v1\"5\n\x05\x46rame\x12\x18\n\x10\x66rame_identifier\x18\x01 \x01(\x04\x12\x12\n\nframe_data\x18\x02 \x01(\x0c\"(\n\x0cPoseResponse\x12\x18\n\x10\x66rame_identifier\x18\x01 \x01(\x04\x32_\n\x0bHeadPoseApi\x12P\n\x07GetPose\x12\x1b.youlearn.headpose.v1.Frame\x1a\".youlearn.headpose.v1.PoseResponse\"\x00(\x01\x30\x01\x42#\n\x10\x63om.youlearn.apiB\rHeadPoseProtoP\x01\x62\x06proto3'
)




_FRAME = _descriptor.Descriptor(
  name='Frame',
  full_name='youlearn.headpose.v1.Frame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='frame_identifier', full_name='youlearn.headpose.v1.Frame.frame_identifier', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='frame_data', full_name='youlearn.headpose.v1.Frame.frame_data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=110,
)


_POSERESPONSE = _descriptor.Descriptor(
  name='PoseResponse',
  full_name='youlearn.headpose.v1.PoseResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='frame_identifier', full_name='youlearn.headpose.v1.PoseResponse.frame_identifier', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=152,
)

DESCRIPTOR.message_types_by_name['Frame'] = _FRAME
DESCRIPTOR.message_types_by_name['PoseResponse'] = _POSERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Frame = _reflection.GeneratedProtocolMessageType('Frame', (_message.Message,), {
  'DESCRIPTOR' : _FRAME,
  '__module__' : 'youlearn.api.pose_service_pb2'
  # @@protoc_insertion_point(class_scope:youlearn.headpose.v1.Frame)
  })
_sym_db.RegisterMessage(Frame)

PoseResponse = _reflection.GeneratedProtocolMessageType('PoseResponse', (_message.Message,), {
  'DESCRIPTOR' : _POSERESPONSE,
  '__module__' : 'youlearn.api.pose_service_pb2'
  # @@protoc_insertion_point(class_scope:youlearn.headpose.v1.PoseResponse)
  })
_sym_db.RegisterMessage(PoseResponse)


DESCRIPTOR._options = None

_HEADPOSEAPI = _descriptor.ServiceDescriptor(
  name='HeadPoseApi',
  full_name='youlearn.headpose.v1.HeadPoseApi',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=154,
  serialized_end=249,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetPose',
    full_name='youlearn.headpose.v1.HeadPoseApi.GetPose',
    index=0,
    containing_service=None,
    input_type=_FRAME,
    output_type=_POSERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_HEADPOSEAPI)

DESCRIPTOR.services_by_name['HeadPoseApi'] = _HEADPOSEAPI

# @@protoc_insertion_point(module_scope)
